stages:
  - prepare
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cachedir/

variables:
  CI_IMAGE: "ravermeister/geneweb"

.imgjob:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  variables:
    DOCKER_DRIVER: overlay2
    BUILDX_VERSION: v0.5.1
  before_script:
    - mkdir utils
    - apk add --no-cache make bash curl jq git
    - mkdir -p ~/.docker/cli-plugins
    - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-arm64
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - echo -n "${CI_REGISTRY_TOKEN}" | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  after_script:
    - docker logout "${CI_REGISTRY}"

prepare:
  stage: prepare
  script:
    - mkdir -p cachedir
    - export GENEWEB_COMMIT_URL="https://api.github.com/repos/geneweb/geneweb/commits?sha=master&per_page=1"
    - export GENEWEB_COMMIT_DATE="$(date '+%Y-%m-%d.%H%M' -d "$(curl -s $GENEWEB_COMMIT_URL | jq --raw-output '.[0].commit.committer.date')")"
    - export GIT_COMMIT_DATE=$(git log -1 --format=%cd --date=format:%Y-%m-%d.%H%M)
    - export BUILD_DATE=$(date '+%Y-%m-%d.%H%M')    
    - echo -n $BUILD_DATE >cachedir/build_date
    - echo -n $GIT_COMMIT_DATE >cachedir/git_commit_date
    - echo -n $GENEWEB_COMMIT_DATE >cachedir/geneweb_commit_date

arm64:
  stage: build
  extends: .imgjob
  tags:
    - arm64
    - docker
  script:
    - docker buildx --pull --no-cache --force-rm --compress -t "$CI_IMAGE:arm64" -f arm64/dockerfile .
    - docker tag "$CI_IMAGE:arm64" "$CI_REGISTRY_IMAGE:arm64"
  only:
    - /^release\/.*$/

arm32:
  stage: build
  extends: .imgjob
  tags:
    - arm32
    - docker
  script:
    - docker buildx --pull --no-cache --force-rm --compress --platform linux/arm/v7 -t "$CI_IMAGE:arm32" -f arm32/dockerfile .
    - docker tag "$CI_IMAGE:arm32" "$CI_REGISTRY_IMAGE:arm32"
  only:
    - /^release\/.*$/
  
publish:
  stage: deploy
  extends: .imgjob
  tags:
    - arm64
    - docker
  script:
    - export BUILD_DATE=$(cat cachedir/build_date)
    - export GIT_COMMIT_DATE=$(cat cachedir/git_commit_date)
    - export GENEWEB_COMMIT_DATE=$(cat cachedir/geneweb_commit_date)
    - docker push "$CI_REGISTRY_IMAGE:arm32"
    - docker push "$CI_REGISTRY_IMAGE:arm64"
    - docker manifest create -a "$CI_REGISTRY_IMAGE:$GENEWEB_COMMIT_DATE" "$CI_REGISTRY_IMAGE:arm32"
    - docker manifest create -a "$CI_REGISTRY_IMAGE:$GENEWEB_COMMIT_DATE" "$CI_REGISTRY_IMAGE:arm64"
    - docker manifest create -a "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:arm32"
    - docker manifest create -a "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:arm64"
    - docker manifest push -p "$CI_REGISTRY_IMAGE:$GENEWEB_COMMIT_DATE"
    - docker manifest push -p "$CI_REGISTRY_IMAGE:latest"
  only:
    - /^release\/.*$/

###########################
