before_script:
  - echo -n "$CI_REGISTRY_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY_SERVER"
  - export GIT_COMMIT_DATE=$(git log -1 --format=%cd --date=format:%Y-%m-%d.%H-%M)
  - export CI_IMAGE="ravermeister/armhf-geneweb"

build-release:
  stage: build
  tags: 
    - arm64
    - shell
  script:
    - docker build --pull --no-cache -t "$CI_IMAGE:$GIT_COMMIT_DATE" .
    - docker tag "$CI_IMAGE:$GIT_COMMIT_DATE" "$CI_REGISTRY_IMAGE:$GIT_COMMIT_DATE"
    - docker tag "$CI_IMAGE:$GIT_COMMIT_DATE" "$CI_REGISTRY_IMAGE:latest"
  only:
    - /^release\/.*$/

publish-release:
  stage: deploy
  tags:
    - arm64
    - shell
  script:
    - docker push "$CI_REGISTRY_IMAGE:$GIT_COMMIT_DATE"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - /^release\/.*$/
###########################

build-feature:
  stage: build
  tags:
    - arm64
    - shell
  script:
    - docker build --pull --no-cache -t "$CI_IMAGE:$GIT_COMMIT_DATE" .
    - docker tag "$CI_IMAGE:$GIT_COMMIT_DATE" "$CI_REGISTRY_IMAGE:$GIT_COMMIT_DATE"
    - docker tag "$CI_IMAGE:$GIT_COMMIT_DATE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^feature\/.*$/

publish-feature:
  stage: deploy
  tags:
    - arm64
    - shell
  script:
    - docker push "$CI_REGISTRY_IMAGE:$GIT_COMMIT_DATE"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^feature\/.*$/
###########################

build-hotfix:
  stage: build
  tags:
    - arm64
    - shell
  script:
    - docker build --pull --no-cache -t "$CI_IMAGE:$GIT_COMMIT_DATE" .
    - docker tag "$CI_IMAGE:$GIT_COMMIT_DATE" "$CI_REGISTRY_IMAGE:$GIT_COMMIT_DATE"
    - docker tag "$CI_IMAGE:$GIT_COMMIT_DATE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^hotfix\/.*$/
    
publish-hotfix:
  stage: deploy
  tags:
    - arm64
    - shell
  script:
    - docker push "$CI_REGISTRY_IMAGE:$GIT_COMMIT_DATE"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^hotfix\/.*$/
###########################

build-develop:
  stage: build
  tags:
    - arm64
    - shell
  script:
    - docker build --pull --no-cache -t "$CI_IMAGE:$GIT_COMMIT_DATE" .
    - docker tag "$CI_IMAGE:$GIT_COMMIT_DATE" "$CI_REGISTRY_IMAGE:$GIT_COMMIT_DATE"
    - docker tag "$CI_IMAGE:$GIT_COMMIT_DATE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^develop\/.*$/
    
publish-develop:
  stage: deploy
  tags:
    - arm64
    - shell
  script:
    - docker push "$CI_REGISTRY_IMAGE:$GIT_COMMIT_DATE"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^develop\/.*$/
###########################
