before_script:
  - echo -n "$CI_REGISTRY_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY_SERVER"
  - export GIT_COMMIT_DATE=$(git log -1 --format=%cd --date=format:%Y-%m-%d.%H%M)
  - export BUILD_DATE=$(date +%Y-%m-%d.%H%M)
  - export CI_IMAGE="ravermeister/armhf-geneweb"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - workdir/

build-release:
  stage: build
  tags: 
    - arm64
    - shell
  script:
    - echo -n $BUILD_DATE >workdir/build_date
    - echo -n $GIT_COMMIT_DATE >workdir/git_commit_date
    - docker build --pull --no-cache -t "$CI_IMAGE:$BUILD_DATE" .
    - docker tag "$CI_IMAGE:$BUILD_DATE" "$CI_REGISTRY_IMAGE:$BUILD_DATE"
    - docker tag "$CI_IMAGE:$BUILD_DATE" "$CI_REGISTRY_IMAGE:latest"
  only:
    - /^release\/.*$/

publish-release:
  stage: deploy
  tags:
    - arm64
    - shell
  script:
    - export BUILD_DATE=$(cat workdir/build_date)
    - export GIT_COMMIT_DATE=$(cat workdir/git_commit_date)
    - docker push "$CI_REGISTRY_IMAGE:$BUILD_DATE"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - /^release\/.*$/

###########################

build-develop:
  stage: build
  tags:
    - arm64
    - shell
  script:
    - echo -n $BUILD_DATE >workdir/build_date
    - echo -n $GIT_COMMIT_DATE >workdir/git_commit_date
    - docker build --pull --no-cache -t "$CI_IMAGE:$BUILD_DATE" .
    - docker tag "$CI_IMAGE:$BUILD_DATE" "$CI_REGISTRY_IMAGE:$BUILD_DATE"
    - docker tag "$CI_IMAGE:$BUILD_DATE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^develop\/.*$/
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    
publish-develop:
  stage: deploy
  tags:
    - arm64
    - shell
  script:
    - export BUILD_DATE=$(cat workdir/build_date)
    - export GIT_COMMIT_DATE=$(cat workdir/git_commit_date)
    - docker push "$CI_REGISTRY_IMAGE:$BUILD_DATE"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - /^develop\/.*$/
    - /^feature\/.*$/
    - /^hotfix\/.*$/

###########################
