version: '3.3'

services:
  geneweb:
    image: ravermeister/geneweb

    # This command is processed by the docker image entrypoint, to launch only
    # the gwd server.
    command: gwd_only

    restart: unless-stopped
    environment:
      - GWD_LANG
    volumes:
      # CONFDIR and DATADIR are defined in .env file
      - ${CONFDIR}:/usr/local/share/geneweb/etc
      - ${DATADIR}:/usr/local/share/geneweb/share/data
      # no need to specify log volume, as all log is directed to standard
      # output, and will be available with "docker-compose logs"
    ports:
        - "${GWD_PORT}:2317"

  geneweb_setup:
    image: ravermeister/geneweb
    command: gwsetup_only
    restart: unless-stopped
    environment:
      - GWSETUP_LANG
    volumes:
      # CONFDIR and DATADIR are defined in .env file
      - ${CONFDIR}:/usr/local/share/geneweb/etc
      - ${DATADIR}:/usr/local/share/geneweb/share/data
      # no need to specify log volume, as all log is directed to standard
      # output, and will be available with "docker-compose logs"
    ports:
        - "$GWSETUP_PORT:2316"
